# Generated by Django 4.2.6 on 2023-12-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CrudRecorridos', '0002_alter_recorridos_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('ingresoID', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('comentario', models.TextField(max_length=50, null=True)),
                ('recorrido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrudRecorridos.recorridos')),
            ],
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('egresoID', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('comentario', models.TextField(max_length=50, null=True)),
                ('recorrido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CrudRecorridos.recorridos')),
            ],
        ),
    ]
