# Generated by Django 4.2.5 on 2023-11-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recorridos',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('conductor', models.CharField(max_length=70)),
                ('fecha', models.DateField()),
                ('ruta', models.CharField(max_length=70)),
                ('cargaTransportada', models.CharField(max_length=70)),
                ('detalleRecorridos', models.TextField(max_length=70)),
            ],
        ),
    ]
