# Generated by Django 4.2.6 on 2023-12-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CrudConductores', '0003_alter_conductores_licencia'),
        ('CrudVehiculos', '0003_remove_vehiculos_comentarios_vehiculos_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorridos',
            fields=[
                ('recorridoID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('direccionOrigen', models.CharField(max_length=50)),
                ('direccionDestino', models.CharField(max_length=50)),
                ('carga', models.TextField(max_length=100)),
                ('detalle', models.TextField(max_length=100)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrudConductores.conductores')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrudVehiculos.vehiculos')),
            ],
        ),
    ]
