# Generated by Django 4.2.6 on 2023-12-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudRecorridos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridos',
            name='detalle',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
