# Generated by Django 5.2.5 on 2025-09-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudRecorridos', '0002_alter_recorridos_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorridos',
            name='distancia_km',
            field=models.FloatField(blank=True, help_text='Distancia recorrida en km', null=True),
        ),
        migrations.AddField(
            model_name='recorridos',
            name='gps_data',
            field=models.JSONField(blank=True, help_text='Datos GPS del recorrido (lista de puntos, GPX, etc)', null=True),
        ),
    ]
