# Generated by Django 4.2.6 on 2023-12-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudVehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=10),
        ),
    ]
