# Generated by Django 5.2.5 on 2025-09-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudVehiculos', '0003_remove_vehiculos_comentarios_vehiculos_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='rendimiento',
            field=models.FloatField(default=10, help_text='Km por litro'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='tipo_bencina',
            field=models.CharField(choices=[('93', '93'), ('95', '95'), ('97', '97'), ('diesel', 'Diésel')], default='93', max_length=10),
        ),
    ]
