# Generated by Django 5.0 on 2023-12-14 16:34

import CrudAtletas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudAtletas', '0002_alter_atleta_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[CrudAtletas.models.validate_rut]),
        ),
    ]
