# Generated by Django 5.0 on 2023-12-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudAtletas', '0004_evento_carrera_evento_lanzamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(),
        ),
    ]
