# Generated by Django 4.2.6 on 2023-12-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('conductorID', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateTimeField()),
                ('direccion', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=10)),
            ],
        ),
    ]
