# Generated by Django 4.2.7 on 2023-11-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateTimeField()),
                ('direccion', models.CharField(max_length=100)),
                ('numeroLicencia', models.CharField(max_length=10)),
                ('otrosDetalles', models.CharField(max_length=100)),
            ],
        ),
    ]
