# Generated by Django 4.2.6 on 2023-12-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudConductores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
    ]
