# Generated by Django 4.2.6 on 2023-12-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudConductores', '0002_alter_conductores_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='licencia',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
