# Generated by Django 4.2.7 on 2023-11-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('patente', models.CharField(max_length=7)),
                ('fechaAdquisicion', models.DateTimeField()),
                ('fechaUltimoMant', models.DateTimeField()),
                ('otrosDetalles', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
