# Generated by Django 4.2.6 on 2023-12-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudMantenciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenciones',
            old_name='fecha',
            new_name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='mantenciones',
            name='codigo',
        ),
        migrations.AddField(
            model_name='mantenciones',
            name='duracion',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenciones',
            name='mantencionID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
